# Generated by Django 5.0.3 on 2024-04-26 18:15

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('currency', models.CharField(max_length=5, verbose_name='Currency')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Rate')),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.models.ModelDisplayMixin, models.Model),
        ),
    ]
