# Generated by Django 5.0.3 on 2024-04-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='used for ordering on main page', verbose_name='Ordering'),
        ),
    ]
