# Generated by Django 5.0.3 on 2024-04-06 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title EN')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Title RU')),
                ('title_kk', models.CharField(max_length=255, verbose_name='Title KK')),
                ('uploaded_file', models.FileField(upload_to='stories/', verbose_name='Uploaded file')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='SeenStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_stories', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_seen', to='stories.story', verbose_name='Story')),
            ],
            options={
                'verbose_name': 'Seen story',
                'verbose_name_plural': 'Seen stories',
                'db_table': 'seen_story',
            },
        ),
    ]
