# Generated by Django 5.0.3 on 2024-04-02 21:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name EN')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Name RU')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Name KK')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description EN')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description RU')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Description KK')),
                ('avg_rate', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Avarage rating')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Location')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='categories.subcategory', verbose_name='Subcategory')),
            ],
            options={
                'verbose_name': 'Attraction',
                'verbose_name_plural': 'Attractions',
                'db_table': 'attraction',
            },
        ),
    ]
