# Generated by Django 5.0.3 on 2024-04-06 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoseAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_chosen', to='attractions.attraction', verbose_name='Attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_attraction', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Attraction chosen',
                'verbose_name_plural': 'Attractions choosen',
                'db_table': 'chosen_attraction',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name EN')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Name RU')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Name KK')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('value_type', models.CharField(choices=[('text', 'Simple text'), ('link', 'Link'), ('phone', 'Phone number')], default='text', max_length=255)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='attractions.attraction', verbose_name='Attraction')),
            ],
            options={
                'verbose_name': 'Attraction detail',
                'verbose_name_plural': 'Attractions details',
                'db_table': 'detail',
            },
        ),
    ]
