# Generated by Django 5.0.3 on 2024-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_choseattraction_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='value',
        ),
        migrations.AddField(
            model_name='attraction',
            name='image',
            field=models.ImageField(default='', upload_to='attractions/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='value_en',
            field=models.CharField(default='', max_length=255, verbose_name='Value EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='value_kk',
            field=models.CharField(default='', max_length=255, verbose_name='Value KK'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='value_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Value RU'),
            preserve_default=False,
        ),
    ]
