# Generated by Django 5.0.3 on 2024-04-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_remove_detail_value_attraction_image_detail_value_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='is_main',
            field=models.BooleanField(default=True, help_text='if checked, then another checked attraction will be unchecked', verbose_name='Show as big'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='is_on_main',
            field=models.BooleanField(default=True, help_text='there can be only 2 checked in one subcategory', verbose_name='Show on main page'),
        ),
    ]
