# Generated by Django 5.0.3 on 2024-04-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_attraction_is_main_attraction_is_on_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
    ]
