# Generated by Django 5.0.3 on 2024-04-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='attraction',
        ),
        migrations.AddField(
            model_name='choseattraction',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='attractions.route', verbose_name='Route'),
        ),
        migrations.AddField(
            model_name='route',
            name='name_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Name EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='name_kk',
            field=models.CharField(default=1, max_length=255, verbose_name='Name KK'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='name_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Name RU'),
            preserve_default=False,
        ),
    ]
