# Generated by Django 5.0.3 on 2024-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0007_remove_route_attraction_choseattraction_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='similar_attractions',
            field=models.ManyToManyField(related_name='similars', to='attractions.attraction', verbose_name='Similar Attractions'),
        ),
    ]
