# Generated by Django 5.0.3 on 2024-06-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0008_attraction_similar_attractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='similar_attractions',
            field=models.ManyToManyField(blank=True, related_name='similars', to='attractions.attraction', verbose_name='Similar Attractions'),
        ),
    ]
