# Generated by Django 5.0.3 on 2024-04-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title EN')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Title RU')),
                ('title_kk', models.CharField(max_length=255, verbose_name='Title KK')),
                ('description_en', models.TextField(verbose_name='Description EN')),
                ('description_ru', models.TextField(verbose_name='Description RU')),
                ('description_kk', models.TextField(verbose_name='Description KK')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Image')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('avg_rate', models.FloatField(default=5.0, verbose_name='Avarage rate')),
                ('way_to_travel', models.CharField(max_length=255, verbose_name='Way to travel')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'db_table': 'tour',
            },
        ),
    ]
