# Generated by Django 5.0.3 on 2024-04-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='way_to_travel',
        ),
        migrations.AddField(
            model_name='tour',
            name='way_to_travel_en',
            field=models.CharField(default='asd', max_length=255, verbose_name='Way to travel EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='way_to_travel_kk',
            field=models.CharField(default='asd', max_length=255, verbose_name='Way to travel KK'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='way_to_travel_ru',
            field=models.CharField(default='asd', max_length=255, verbose_name='Way to travel RU'),
            preserve_default=False,
        ),
    ]
